source: CLOUD_PRODUCTION_SHARD1
target: SLING_DB_SHARD1
defaults:
  mode: incremental
  object: '{stream_table}'
  update_key: id
  source_options:
    limit: 500000

streams:
  public.run_tags:
    meta:
      dagster:
        asset_key: sling.cloud_product_shard1.run_tags

  public.alert_policies:
    meta:
      dagster:
        asset_key: sling.cloud_product_shard1.alert_policies

  public.job_ticks_ptn:
    sql: >
      with candidates as (
        select *
        from public.job_ticks_ptn
        where id > coalesce({incremental_value}, 17004308455)
        order by id
        limit 500000
      )
      select * from candidates
    meta:
      dagster:
        asset_key: sling.cloud_product_shard1.job_ticks_ptn
