source: PURINA_CLOUD_REPORTING
target: REPORTING_DB
defaults:
  mode: truncate
  object: '{stream_table}'

streams:
  purina.product.enterprise_contract_metadata:
    object: public.enterprise_contract_metadata
    meta:
      dagster:
        asset_key: public.enterprise_contract_metadata
