source: PURINA_CLOUD_REPORTING
target: REPORTING_DB
defaults:
  mode: truncate
  object: '{stream_table}'

streams:
  purina.product.enterprise_contract_metadata:
    object: public.enterprise_contract_metadata
    sql: |
      SELECT
        ORGANIZATION_ID,
        CREDITS_DATE,
        CUMULATIVE_CREDITS_USED,
        ANNUAL_CLOUD_CREDITS_CONTRACT,
        CLOUD_CREDITS_CONTRACTED_WITH_ROLLOVER,
        CONTRACT_START_DATE,
        CONTRACT_END_DATE,
        LAUNCHER_SEATS,
        PER_CREDIT_PRICE_USD,
        PER_SEAT_PRICE_USD,
        ANNUAL_SERVERLESS_MINUTES_CONTRACT,
        CUMULATIVE_SERVERLESS_MINUTES_USED
      FROM purina.product.enterprise_contract_metadata
    meta:
      dagster:
        asset_key: public.enterprise_contract_metadata
