select

    id as subscription_id,
    customer_id,

    application_fee_percent,
    billing,
    billing_cycle_anchor,
    billing_thresholds_amount_gte,
    billing_thresholds_reset_billing_cycle_anchor,
    cancel_at,
    cancel_at_period_end,
    canceled_at,
    cancellation_reason,
    cancellation_reason_text,
    created as created_at,
    current_period_end,
    current_period_start,
    days_until_due,
    default_payment_method_id,
    default_source_id,
    discount_coupon_id,
    discount_customer_id,
    discount_end,
    discount_start,
    discount_subscription,
    ended_at,
    merchant_id,
    pause_collection_behavior,
    pause_collection_resumes_at,
    plan_id,
    price_id,
    quantity,
    start_date,
    start_time,
    status,
    tax_percent,
    trial_end,
    trial_start

from {{ source('stripe_pipeline', 'subscriptions') }}
